live_config_reload: true
shell:
  program: "/bin/zsh"
  args:
    - "-l"

scrolling:
  history: 5000
  multiplier: 20

window:
  decorations: "Transparent"
  dynamic_padding: true
  startup_mode: "Windowed"
  opacity: 0.96
  option_as_alt: Both
  padding:
    x: 6
    y: 20
  dimensions:
    columns: 120
    lines: 60

font:
  size: 14
  normal:
    family: "JetbrainsMono Nerd Font"
    style: "Regular"

import:
  - ~/.config/alacritty/themes/themes/nord.yaml
