live_config_reload = true
# tabspaces = 4

[scrolling]
# auto_scroll = true
# faux_multiplier = 100
history = 2000
multiplier = 20

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Maximized"
opacity = 0.96

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 10
y = 15

[font]
size = 12
[font.normal]
family= "JetBrainsMono Nerd Font"
style = "Regular"
