live_config_reload = true
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
general.import = [
    # "~/.config/alacritty/catppuccin-latte.toml",
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml",
]
# tabspaces = 4

[scrolling]
# auto_scroll = true
# faux_multiplier = 100
history = 2000
multiplier = 20

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
decorations = "Full"
dynamic_padding = false
startup_mode = "Maximized"
opacity = 0.99

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 10
y = 5

[font]
size = 12
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
